### ISSUE TITLE
Not allowing me to 'Upsert' anything

### ISSUE THREAD

**Issue by ThamanVelasquezBice** [austinkregel/Warden#5]
Whenever I try to submit items to the database it throws a fit.

```
'ReflectionException in Container.php line 734:
Class does not exist'
```

**Comment by austinkregel** [comment]
That's not really helpful, can you truncate your `storage/logs/laravel.log` (you can use `truncate storage/logs/laravel.log --size=0` if you're on linux) and then try doing whatever you were doing again. Then post the contents of your error here. Please and thank you :D

**Comment by ThamanVelasquezBice** [comment]
This may be what you are looking for(?)

```
local.ERROR: ReflectionException: Class  does not exist in                           
/home/forge/projectname/vendor/laravel/framework/src/Illuminate/Container/Container.php:734
```

**Comment by austinkregel** [comment]
Is that the whole file? It's still not helpful :/

**Comment by ThamanVelasquezBice** [comment]
Oh, didn't realize you wanted the entire file. 

```
[2016-06-03 15:32:05] local.ERROR: ReflectionException: Class  does not exist in /home/forge/realchek_remake.ved/vendor/laravel/framework/src/Illuminate/Container/Container.php:734
Stack trace:
#0 /home/forge/realchek_remake.ved/vendor/laravel/framework/src/Illuminate/Container/Container.php(734): ReflectionClass->__construct('')
#1 /home/forge/realchek_remake.ved/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build('', Array)
#2 /home/forge/realchek_remake.ved/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('', Array)
#3 /home/forge/realchek_remake.ved/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(126): Illuminate\Foundation\Application->make('')
#4 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#5 /home/forge/realchek_remake.ved/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#6 /home/forge/realchek_remake.ved/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(48): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#7 [internal function]: Illuminate\Routing\Middleware\ThrottleRequests->handle(Object(Illuminate\Http\Request), Object(Closure), '60', '1')
#8 /home/forge/realchek_remake.ved/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#9 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#10 /home/forge/realchek_remake.ved/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#11 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 /home/forge/realchek_remake.ved/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#13 /home/forge/realchek_remake.ved/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#14 /home/forge/realchek_remake.ved/vendor/laravel/framework/src/Illuminate/Routing/Router.php(699): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#15 /home/forge/realchek_remake.ved/vendor/laravel/framework/src/Illuminate/Routing/Router.php(675): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#16 /home/forge/realchek_remake.ved/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(246): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#17 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#18 /home/forge/realchek_remake.ved/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#19 /home/forge/realchek_remake.ved/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 /home/forge/realchek_remake.ved/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#22 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 /home/forge/realchek_remake.ved/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#24 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 /home/forge/realchek_remake.ved/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#26 /home/forge/realchek_remake.ved/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#27 /home/forge/realchek_remake.ved/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#28 /home/forge/realchek_remake.ved/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#29 {main}  
[2016-06-03 15:32:05] local.ERROR: ReflectionException: Class  does not exist in /home/forge/realchek_remake.ved/vendor/laravel/framework/src/Illuminate/Container/Container.php:734
Stack trace:
#0 /home/forge/realchek_remake.ved/vendor/laravel/framework/src/Illuminate/Container/Container.php(734): ReflectionClass->__construct('')
#1 /home/forge/realchek_remake.ved/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build('', Array)
#2 /home/forge/realchek_remake.ved/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('', Array)
#3 /home/forge/realchek_remake.ved/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(152): Illuminate\Foundation\Application->make('')
#4 /home/forge/realchek_remake.ved/public/index.php(58): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#5 {main}  
```

**Comment by austinkregel** [comment]
which branch are you using? (Which version are you using?)

**Comment by ThamanVelasquezBice** [comment]
5.2

**Comment by austinkregel** [comment]
Looks like you might have a blank string somewhere. Look in your `config/kregel/warden.php` file and make sure your model's all have a `model` sub key and make sure your middlewares are not blank strings, if your middlewares are blank strings, turn them into empty arrays. If your models don't have a model class, delete them from the config.

**Comment by ThamanVelasquezBice** [comment]
Oh, my middleware api was an empty string, not an empty array. Fixed when it was changed to an empty array :3

**Comment by austinkregel** [comment]
Cool, I'm glad you got it fixed!
